spring:
  cloud:
    gateway:
      routes:
        - id: tamachi
          uri: http://tamachi:8081
          predicates:
          - Method=GET
          - After=2020-03-14T00:00:00.000+09:00[Asia/Tokyo]
          - Header=JR-Yamanote-Line
          - Host=tamachi
        - id: shinagawa
          uri: http://shinagawa:8081
          predicates:
            - Method=GET
            - After=2020-03-14T00:00:00.000+09:00[Asia/Tokyo]
            - Header=JR-Yamanote-Line
            - Host=shinagawa,**
